# Generated by Django 4.2.10 on 2024-03-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeLink',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
