# Generated by Django 4.2.10 on 2024-03-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubelink',
            old_name='link',
            new_name='link_id',
        ),
    ]
