# Generated by Django 4.2.10 on 2024-03-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_rename_link_youtubelink_link_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YoutubeLink',
            new_name='Transcipt',
        ),
    ]
