# Generated by Django 4.2.10 on 2024-03-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='link_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
